// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmm4urYdmRwkIjVBNg7JsP0b7K0wbNKs0',
    appId: '1:296650236210:web:69f8f289786c6f7546372b',
    messagingSenderId: '296650236210',
    projectId: 'holbegram-e8f1f',
    authDomain: 'holbegram-e8f1f.firebaseapp.com',
    storageBucket: 'holbegram-e8f1f.appspot.com',
    measurementId: 'G-KSC3EW7YL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHW0pHbu3ldw9XdLYYZUPFJWu6Af6IEJE',
    appId: '1:296650236210:android:154a5e0e6306aa9f46372b',
    messagingSenderId: '296650236210',
    projectId: 'holbegram-e8f1f',
    storageBucket: 'holbegram-e8f1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSAb9b1pNTZ2Q4ArstA5BTcOml3FwUp-s',
    appId: '1:296650236210:ios:8b56600125b5ab7a46372b',
    messagingSenderId: '296650236210',
    projectId: 'holbegram-e8f1f',
    storageBucket: 'holbegram-e8f1f.appspot.com',
    iosBundleId: 'com.example.holbegrame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSAb9b1pNTZ2Q4ArstA5BTcOml3FwUp-s',
    appId: '1:296650236210:ios:8fd4ffa43a5cf06446372b',
    messagingSenderId: '296650236210',
    projectId: 'holbegram-e8f1f',
    storageBucket: 'holbegram-e8f1f.appspot.com',
    iosBundleId: 'com.example.holbegrame.RunnerTests',
  );
}
